development:
  stripe_secret_key: 'sk_test_UBZOkZMyPv5Mf1uZrxgAXQjP005OYvYkfN'
  stripe_publishable_key: 'pk_test_nM7VaB7XTlhd7eg7AT7yuc1a00bJnb2C3D'

production:
  stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
  stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'